### ISSUE TITLE
[Task] Back-end DB연결 테스트 및 폴더구조 세부작업

### ISSUE THREAD

**Issue by goodbsm2421** [codestates/Keyplus#10]
### TO-DO
- [x] Controller 폴더 API 로직 수도코드 작성
- [x] 데이터베이스 로컬환경에서 연결 및 테스트
- [x] 데이터베이스 테이블 구축 및 관계설정
