### ISSUE TITLE
[Task] 최종 정리

### ISSUE THREAD

**Issue by seona-jung** [codestates/Keyplus#142]
### TO-DO
- [x] Bug Check
- [x] [Wiki] Front-end Flowchart 수정
- [x] [Wiki] Back-end Flowchart 수정
- [x] [Wiki] System Architecture 수정
- [x] [Wiki] API Document 수정
- [x] [Notion] 개인별 작업 정리
- [x] [Notion] 기능 시연 GIF 생성
