### ISSUE TITLE
[Task] Back-end SR 작업 

### ISSUE THREAD

**Issue by goodbsm2421** [codestates/Keyplus#4]
### TO-DO
- [x] API Documents
- [x] System architecture
- [x] Server flow chart
- [x] 폴더 구조 잡기
- [x] Task Card 발행
