### ISSUE TITLE
[Task] Landing Page

### ISSUE THREAD

**Issue by seona-jung** [codestates/Keyplus#71]
### TO-DO
- [x] 랜딩 페이지 구상
- [x] 이미지 캐러셀 구현
- [x] 소개 문구 추가
- [x] 애니메이션 추가 (aos library)
- [x] 반응형 디자인
